module.exports = {
	areReferencesModified: require(__dirname + '/areReferencesModified'),
	canUnaryExpressionBeResolved: require(__dirname + '/canUnaryExpressionBeResolved'),
	createNewNode: require(__dirname + '/createNewNode'),
	createOrderedSrc: require(__dirname + '/createOrderedSrc'),
	doesBinaryExpressionContainOnlyLiterals: require(__dirname + '/doesBinaryExpressionContainOnlyLiterals'),
	evalInVm: require(__dirname + '/evalInVm'),
	evalWithDom: require(__dirname + '/evalWithDom'),
	generateHash: require(__dirname + '/generateHash'),
	getCache: require(__dirname + '/getCache'),
	getCalleeName: require(__dirname + '/getCalleeName'),
	getDeclarationWithContext: require(__dirname + '/getDeclarationWithContext'),
	getDescendants: require(__dirname + '/getDescendants'),
	getMainDeclaredObjectOfMemberExpression: require(__dirname + '/getMainDeclaredObjectOfMemberExpression'),
	getObjType: require(__dirname + '/getObjType'),
	isNodeInRanges: require(__dirname + '/isNodeInRanges'),
	isNodeMarked: require(__dirname + '/isNodeMarked'),
	normalizeScript: require(__dirname + '/normalizeScript'),
	safeImplementations: require(__dirname + '/safeImplementations'),
	sandbox: require(__dirname + '/sandbox'),
};